version: "1"
rules:
  - base: 1.20.6
    upstream: cabaletta:1.20.6
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.20.5
    upstream: cabaletta:1.20.5
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.20.4
    upstream: cabaletta:1.20.4
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.20.3
    upstream: cabaletta:1.20.3
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.20.2
    upstream: cabaletta:1.20.2
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.20.1
    upstream: cabaletta:1.20.1
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.21
    upstream: cabaletta:1.21
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: Meteor
    upstream: MeteorDevelopment:1.20.6
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
label: ":arrow_heading_down: pull",
onflictLabel: "merge-conflict"