# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 1.18 ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: 给予gradlew的执行许可
      run: chmod +x gradlew
      
    - name: 用Gradle构建
      run: ./gradlew build

    - name: 用Gradle构建（结构）。
      run: ./gradlew build -Pbaritone.fabric_build

    - name: 用Gradle构建（锻造）
      run: ./gradlew build -Pbaritone.forge_build -Ploom.platform=forge
    - name: 自动释放
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "java"
        prerelease: true
        title: "baritone Automatic build versions"
        files: |
          dist/*
          build/tmp/proguard/mapping.txt
